In [1]:
from pathlib import Path
import pandas as pd
import numpy as np

In [5]:
PROJECT_DIR = Path("../")

RAW_DATA_DIR = PROJECT_DIR / "data" / "raw"
PROCESSED_DATA_DIR = PROJECT_DIR / "data" / "processed"

TRAIN_PATH = RAW_DATA_DIR / "train.csv"
TEST_PATH = RAW_DATA_DIR / "test.csv"

PROCESSED_DATA_DIR.mkdir(parents=True, exist_ok=True)

print("Project exists:", PROJECT_DIR.exists())
print("Train exists:", TRAIN_PATH.exists())
print("Test exists:", TEST_PATH.exists())

Project exists: True
Train exists: True
Test exists: True

In [6]:
train_df = pd.read_csv(TRAIN_PATH)

print("Train shape:", train_df.shape)
display(train_df.head())
print(train_df.columns.tolist())

Train shape: (9500, 3)

,id,prompt,answer
0,00066667,"In Alice's Wonderland, a secret bit manipulati...",10010111
1,000b53cf,"In Alice's Wonderland, a secret bit manipulati...",01000011
2,00189f6a,"In Alice's Wonderland, secret encryption rules...",cat imagines book
3,001b24c4,"In Alice's Wonderland, numbers are secretly co...",XXXVIII
4,001c63cb,"In Alice's Wonderland, secret encryption rules...",wizard creates secret

['id', 'prompt', 'answer']

In [7]:
print("Rows:", train_df.shape[0])
print("Columns:", train_df.shape[1])

display(train_df.info())

missing = train_df.isna().sum().reset_index()
missing.columns = ["column", "missing_count"]
missing["missing_percent"] = (missing["missing_count"] / len(train_df) * 100).round(2)

display(missing.sort_values("missing_count", ascending=False))

print("Duplicate rows:", train_df.duplicated().sum())

Rows: 9500
Columns: 3
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9500 entries, 0 to 9499
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      9500 non-null   object
 1   prompt  9500 non-null   object
 2   answer  9500 non-null   object
dtypes: object(3)
memory usage: 222.8+ KB

None

   column  missing_count  missing_percent
0      id              0              0.0
1  prompt              0              0.0
2  answer              0              0.0

Duplicate rows: 0

In [8]:
def find_column(df, possible_names):
    columns_lower = {col.lower(): col for col in df.columns}
    
    for name in possible_names:
        if name.lower() in columns_lower:
            return columns_lower[name.lower()]
    
    return None


prompt_col = find_column(
    train_df,
    ["prompt", "question", "puzzle", "input", "problem"]
)

answer_col = find_column(
    train_df,
    ["answer", "target", "output", "solution", "label"]
)

print("Prompt column:", prompt_col)
print("Answer column:", answer_col)

if prompt_col is None:
    raise ValueError(f"Could not find prompt column. Columns: {train_df.columns.tolist()}")

if answer_col is None:
    raise ValueError(f"Could not find answer column. Columns: {train_df.columns.tolist()}")

Prompt column: prompt
Answer column: answer

In [9]:
pd.set_option("display.max_colwidth", 1000)

display(train_df[[prompt_col, answer_col]].head(10))

,prompt,answer
0,"In Alice's Wonderland, a secret bit manipulation rule transforms 8-bit binary numbers. The transformation involves operations like bit shifts, rotations, XOR, AND, OR, NOT, and possibly majority or choice functions.\n\nHere are some examples of input -> output:\n01010001 -> 11011101\n00001001 -> 01101101\n00010101 -> 01010101\n11111111 -> 10000001\n10011101 -> 01000101\n00111011 -> 00001001\n10111101 -> 00000101\n00100110 -> 10110011\n\nNow, determine the output for: 00110100",10010111
1,"In Alice's Wonderland, a secret bit manipulation rule transforms 8-bit binary numbers. The transformation involves operations like bit shifts, rotations, XOR, AND, OR, NOT, and possibly majority or choice functions.\n\nHere are some examples of input -> output:\n10001110 -> 00100110\n10011001 -> 01000100\n01100100 -> 00010001\n10000010 -> 00001010\n00011011 -> 01001100\n00111010 -> 10011100\n01101111 -> 00110111\n10010110 -> 01011010\n00001010 -> 00101100\n\nNow, determine the output for: 11100000",01000011
2,"In Alice's Wonderland, secret encryption rules are used on text. Here are some examples:\nucoov pwgtfyoqg vorq yrjjoe -> queen discovers near valley\npqrsfv pqorzg wvgwpo trgbjo -> dragon dreams inside castle\ngbcpovb tqorbog bxo zrswtrj pffq -> student creates the magical door\nbxo sfjpov pqrsfv dfjjfig -> the golden dragon follows\nnqwvtogg qorpg bxo zegboqwfcg gotqob -> princess reads the mysterious secret\nNow, decrypt the following text: trb wzrswvog hffk",cat imagines book
3,"In Alice's Wonderland, numbers are secretly converted into a different numeral system. Some examples are given below:\n11 -> XI\n15 -> XV\n94 -> XCIV\n19 -> XIX\nNow, write the number 38 in the Wonderland numeral system.",XXXVIII
4,"In Alice's Wonderland, secret encryption rules are used on text. Here are some examples:\nwkgqa lsrqaq wneeke -> mouse chases mirror\nwkgqa nwrjnvaq nv brmrla -> mouse imagines in palace\nsrppae oerhq gvoae wkgvprnv -> hatter draws under mountain\npsa qaleap hncreo onqlkzaeq -> the secret wizard discovers\npsa hnqa xneo earoq -> the wise bird reads\nNow, decrypt the following text: hncreo learpaq qaleap",wizard creates secret
5,"In Alice's Wonderland, a secret unit conversion is applied to measurements. For example:\n10.08 m becomes 6.69\n17.83 m becomes 11.83\n35.85 m becomes 23.79\n17.06 m becomes 11.32\n31.54 m becomes 20.93\nNow, convert the following measurement: 25.09 m",16.65
6,"In Alice's Wonderland, a secret bit manipulation rule transforms 8-bit binary numbers. The transformation involves operations like bit shifts, rotations, XOR, AND, OR, NOT, and possibly majority or choice functions.\n\nHere are some examples of input -> output:\n00000000 -> 00000000\n11001011 -> 11110010\n11110010 -> 10111100\n01001000 -> 00010010\n01101000 -> 00011010\n01011101 -> 01010111\n10111001 -> 01101110\n11011111 -> 11110111\n11110101 -> 01111101\n01111001 -> 01011110\n\nNow, determine the output for: 11010000",00110100
7,"In Alice's Wonderland, the gravitational constant has been secretly changed. Here are some example observations:\nFor t = 1.37s, distance = 14.92 m\nFor t = 4.27s, distance = 144.96 m\nFor t = 3.28s, distance = 85.54 m\nFor t = 3.67s, distance = 107.09 m\nFor t = 1.78s, distance = 25.19 m\nNow, determine the falling distance for t = 4.41s given d = 0.5*g*t^2.",154.62
8,"In Alice's Wonderland, a secret set of transformation rules is applied to equations. Below are a few examples:\n`!*[{ = '""[`\n\'*'> = ![@\n\'-!` = \\\n`!*\& = '@'{\nNow, determine the result for: [[-!'",@&
9,"In Alice's Wonderland, the gravitational constant has been secretly changed. Here are some example observations:\nFor t = 4.85s, distance = 204.55 m\nFor t = 3.13s, distance = 85.19 m\nFor t = 1.7s, distance = 25.13 m\nFor t = 3.16s, distance = 86.84 m\nFor t = 3.23s, distance = 90.73 m\nNow, determine the falling distance for t = 2.41s given d = 0.5*g*t^2.",50.51

In [10]:
baseline_df = train_df[[prompt_col, answer_col]].copy()

baseline_df.columns = ["prompt", "answer"]

baseline_df["prompt"] = baseline_df["prompt"].astype(str).str.strip()
baseline_df["answer"] = baseline_df["answer"].astype(str).str.strip()

baseline_df = baseline_df.dropna()
baseline_df = baseline_df.drop_duplicates()

print("Clean baseline shape:", baseline_df.shape)
display(baseline_df.head())

Clean baseline shape: (9500, 2)

,prompt,answer
0,"In Alice's Wonderland, a secret bit manipulation rule transforms 8-bit binary numbers. The transformation involves operations like bit shifts, rotations, XOR, AND, OR, NOT, and possibly majority or choice functions.\n\nHere are some examples of input -> output:\n01010001 -> 11011101\n00001001 -> 01101101\n00010101 -> 01010101\n11111111 -> 10000001\n10011101 -> 01000101\n00111011 -> 00001001\n10111101 -> 00000101\n00100110 -> 10110011\n\nNow, determine the output for: 00110100",10010111
1,"In Alice's Wonderland, a secret bit manipulation rule transforms 8-bit binary numbers. The transformation involves operations like bit shifts, rotations, XOR, AND, OR, NOT, and possibly majority or choice functions.\n\nHere are some examples of input -> output:\n10001110 -> 00100110\n10011001 -> 01000100\n01100100 -> 00010001\n10000010 -> 00001010\n00011011 -> 01001100\n00111010 -> 10011100\n01101111 -> 00110111\n10010110 -> 01011010\n00001010 -> 00101100\n\nNow, determine the output for: 11100000",01000011
2,"In Alice's Wonderland, secret encryption rules are used on text. Here are some examples:\nucoov pwgtfyoqg vorq yrjjoe -> queen discovers near valley\npqrsfv pqorzg wvgwpo trgbjo -> dragon dreams inside castle\ngbcpovb tqorbog bxo zrswtrj pffq -> student creates the magical door\nbxo sfjpov pqrsfv dfjjfig -> the golden dragon follows\nnqwvtogg qorpg bxo zegboqwfcg gotqob -> princess reads the mysterious secret\nNow, decrypt the following text: trb wzrswvog hffk",cat imagines book
3,"In Alice's Wonderland, numbers are secretly converted into a different numeral system. Some examples are given below:\n11 -> XI\n15 -> XV\n94 -> XCIV\n19 -> XIX\nNow, write the number 38 in the Wonderland numeral system.",XXXVIII
4,"In Alice's Wonderland, secret encryption rules are used on text. Here are some examples:\nwkgqa lsrqaq wneeke -> mouse chases mirror\nwkgqa nwrjnvaq nv brmrla -> mouse imagines in palace\nsrppae oerhq gvoae wkgvprnv -> hatter draws under mountain\npsa qaleap hncreo onqlkzaeq -> the secret wizard discovers\npsa hnqa xneo earoq -> the wise bird reads\nNow, decrypt the following text: hncreo learpaq qaleap",wizard creates secret

In [11]:
SYSTEM_PROMPT = """You are solving a reasoning puzzle.
Return only the final answer."""


def format_sft_text(prompt, answer):
    return f"""{SYSTEM_PROMPT}

Puzzle:
{prompt}

Answer:
{answer}"""


baseline_df["text"] = baseline_df.apply(
    lambda row: format_sft_text(row["prompt"], row["answer"]),
    axis=1
)

display(baseline_df[["text"]].head())

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         text
0                        You are solving a reasoning puzzle.\nReturn only the final answer.\n\nPuzzle:\nIn Alice's Wonderland, a secret bit manipulation rule transforms 8-bit binary numbers. The transformation involves operations like bit shifts, rotations, XOR, AND, OR, NOT, and possibly majority or choice functions.\n\nHere are some examples of input -> output:\n01010001 -> 11011101\n00001001 -> 01101101\n00010101 -> 01010101\n11111111 -> 10000001\n10011101 -> 01000101\n00111011 -> 00001001\n10111101 -> 00000101\n00100110 -> 10110011\n\nNow, determine the output for: 00110100\n\nAnswer:\n10010111
1  You are solving a reasoning puzzle.\nReturn only the final answer.\n\nPuzzle:\nIn Alice's Wonderland, a secret bit manipulation rule transforms 8-bit binary numbers. The transformation involves operations like bit shifts, rotations, XOR, AND, OR, NOT, and possibly majority or choice functions.\n\nHere are some examples of input -> output:\n10001110 -> 00100110\n10011001 -> 01000100\n01100100 -> 00010001\n10000010 -> 00001010\n00011011 -> 01001100\n00111010 -> 10011100\n01101111 -> 00110111\n10010110 -> 01011010\n00001010 -> 00101100\n\nNow, determine the output for: 11100000\n\nAnswer:\n01000011
2                               You are solving a reasoning puzzle.\nReturn only the final answer.\n\nPuzzle:\nIn Alice's Wonderland, secret encryption rules are used on text. Here are some examples:\nucoov pwgtfyoqg vorq yrjjoe -> queen discovers near valley\npqrsfv pqorzg wvgwpo trgbjo -> dragon dreams inside castle\ngbcpovb tqorbog bxo zrswtrj pffq -> student creates the magical door\nbxo sfjpov pqrsfv dfjjfig -> the golden dragon follows\nnqwvtogg qorpg bxo zegboqwfcg gotqob -> princess reads the mysterious secret\nNow, decrypt the following text: trb wzrswvog hffk\n\nAnswer:\ncat imagines book
3                                                                                                                                                                                                                                                                                             You are solving a reasoning puzzle.\nReturn only the final answer.\n\nPuzzle:\nIn Alice's Wonderland, numbers are secretly converted into a different numeral system. Some examples are given below:\n11 -> XI\n15 -> XV\n94 -> XCIV\n19 -> XIX\nNow, write the number 38 in the Wonderland numeral system.\n\nAnswer:\nXXXVIII
4                                                                                     You are solving a reasoning puzzle.\nReturn only the final answer.\n\nPuzzle:\nIn Alice's Wonderland, secret encryption rules are used on text. Here are some examples:\nwkgqa lsrqaq wneeke -> mouse chases mirror\nwkgqa nwrjnvaq nv brmrla -> mouse imagines in palace\nsrppae oerhq gvoae wkgvprnv -> hatter draws under mountain\npsa qaleap hncreo onqlkzaeq -> the secret wizard discovers\npsa hnqa xneo earoq -> the wise bird reads\nNow, decrypt the following text: hncreo learpaq qaleap\n\nAnswer:\nwizard creates secret

In [12]:
baseline_df["prompt_length"] = baseline_df["prompt"].str.len()
baseline_df["answer_length"] = baseline_df["answer"].str.len()
baseline_df["text_length"] = baseline_df["text"].str.len()

display(
    baseline_df[
        ["prompt_length", "answer_length", "text_length"]
    ].describe()
)

       prompt_length  answer_length  text_length
count    9500.000000    9500.000000  9500.000000
mean      301.515895       8.393789   394.909684
std       104.265311       8.035097   108.104165
min       177.000000       1.000000   266.000000
25%       209.000000       4.000000   298.000000
50%       281.000000       5.000000   372.000000
75%       371.000000       8.000000   481.000000
max       510.000000      39.000000   603.000000

### Train

In [13]:
from sklearn.model_selection import train_test_split

train_sft_df, val_sft_df = train_test_split(
    baseline_df,
    test_size=0.05,
    random_state=42,
    shuffle=True
)

print("Train SFT shape:", train_sft_df.shape)
print("Validation SFT shape:", val_sft_df.shape)

Train SFT shape: (9025, 6)
Validation SFT shape: (475, 6)

In [ ]:
train_sft_path = PROCESSED_DATA_DIR / "train_sft.csv"
val_sft_path = PROCESSED_DATA_DIR / "val_sft.csv"
full_sft_path = PROCESSED_DATA_DIR / "full_sft.csv"

train_sft_df.to_csv(train_sft_path, index=False)
val_sft_df.to_csv(val_sft_path, index=False)
baseline_df.to_csv(full_sft_path, index=False)

print("Saved:")
print(train_sft_path)
print(val_sft_path)
print(full_sft_path)

In [14]:
train_jsonl_path = PROCESSED_DATA_DIR / "train_sft.jsonl"
val_jsonl_path = PROCESSED_DATA_DIR / "val_sft.jsonl"

train_sft_df[["text"]].to_json(
    train_jsonl_path,
    orient="records",
    lines=True,
    force_ascii=False
)

val_sft_df[["text"]].to_json(
    val_jsonl_path,
    orient="records",
    lines=True,
    force_ascii=False
)

print("Saved JSONL:")
print(train_jsonl_path)
print(val_jsonl_path)

Saved JSONL:
..\data\processed\train_sft.jsonl
..\data\processed\val_sft.jsonl